services:
  - docker

dist: trusty
cache: bundler

env:
  global:
    - KAFKA_HEAP_OPTS="-Xmx512m -Xms512m"

git:
  depth: false

test: &test
  stage: Test
  language: ruby
  before_install:
    - yes | gem update --system
  before_script:
    - docker-compose up -d

  script: bundle exec rspec

  after_script:
    - docker-compose stop

jobs:
  include:
    - <<: *test
      rvm: 2.6.5
    - <<: *test
      rvm: 2.5.7

    - stage: coditsu
      language: ruby
      rvm: 2.6.5
      before_install:
        - yes | gem update --system
      script: \curl -sSL https://api.coditsu.io/run/ci | bash

stages:
  - test
  - coditsu
